### ISSUE TITLE
Event variable errors

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/extcal#13]
Tried this extcal version:
https://github.com/mambax7/extcal/tree/67f8ad08dc9b0a1899609cbb55f70a3ec7f74810

When I create an event on admin side, I get these errors (please take a look at the screenshots):

![image](https://cloud.githubusercontent.com/assets/4613970/24328797/e6ec7456-11f3-11e7-8037-609bd3070d69.png)

![image](https://cloud.githubusercontent.com/assets/4613970/24328890/6149e560-11f6-11e7-8932-10a509974799.png)

___
My config:
XOOPS Version	XOOPS 2.5.9-Beta2
PHP Version	7.0.15-0ubuntu0.16.10.4
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by mambax7** [comment]
Seems to be working now
