### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/extcal#16]
The problem with Russian localization:
![cyrillic](https://user-images.githubusercontent.com/25700040/31114605-9f36567a-a827-11e7-8b5f-7054d279a2ba.png)
Encoding in ISO

**Comment by mambax7** [comment]
You should use UTF-8

**Comment by aerograf** [comment]
I wrote incorrectly.
I use UTF-8, but the pseudo-graphic is just in ISO.
Such a problem in the calendar for a month and a week ....

**Comment by mambax7** [comment]
Check your encoding in the DB templates - maybe it's not UTF-8?

**Comment by mambax7** [comment]
Should be fixed now in: https://github.com/mambax7/extcal/commit/4e70f679abc5d91a6a7b7e54e4ab93781ebbdbb3
Please test

**Comment by aerograf** [comment]
Yes. It works. Thank you!
