### ISSUE TITLE
Waiting event does not appear in the administration

### ISSUE THREAD

**Issue by bioskop2** [XoopsModules25x/extcal#19]
Hello !

eXtCal 2.40 Beta 2 (but idem with 2.39 final)

When an event is not automatically validated, it does not appear in administration. It is nowhere in the admin, impossible to validate, edit or anything ...
But it is present in the database
Thank you for your help !

-----
XOOPS 2.5.10
PHP 7.2.24
mySQL | 5.6.41-log

**Comment by bioskop2** [comment]
Thanks Michael,
Looking good, it appears that the pending events are visible via this page : /extcal/admin/main.php
This file could replace /extcal/admin/index.php? Or it is an old file?
Vincent

**Comment by bioskop2** [comment]
/extcal/admin/main.php is an old file from before version 2.39, not present in recent version

**Comment by mambax7** [comment]
It's should work now. Please re-open, if it doesn't
