### ISSUE TITLE
Cosmetic

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/extcal#21]
Just some cosmetic issue in few pages.
Like here : https://github.com/XOOPS/XoopsCore25/issues/649
For exemple, in admin page, icones action on the right, there is a link for a space between each icones.

I cant propose commit before tonight or tomorrow

**Comment by mambax7** [comment]
Please create separate issues for the next release and label them as bugs or as enhancements.
Thank you!

**Comment by alain01** [comment]
linked to the Pull request https://github.com/XoopsModules25x/extcal/pull/22
