### ISSUE TITLE
Cosmetics on /modules/extcal/view_new-event.php

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/extcal#23]
3 mini cosmtic errors

- Yellow : space between months
- Green : 2 times the label "Attach a file"
- Orange : space after the files form

![Annotation 2020-06-04 010937](https://user-images.githubusercontent.com/5336960/83697855-4a996880-a600-11ea-9e5d-7d103de286d8.png)

**Comment by mambax7** [comment]
fixed in https://github.com/XoopsModules25x/extcal/pull/35
![image](https://user-images.githubusercontent.com/613686/86996930-e592de80-c17a-11ea-864a-161eaadeaaf8.png)
