### ISSUE TITLE
Default rights with sample datas

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/extcal#24]
With the sample data : 
For the both categories : admins group has no premission to view
So, when i clicked on an event, on the /modules/extcal/admin/event.php page, nothing appears.

All is ok if i put manually the permission on the categories.

No problem with empty datas on fresh install
I can add a category and the permission is ok for admins group.
So, just with sample data.

**Comment by mambax7** [comment]
This should fix it: https://github.com/XoopsModules25x/extcal/pull/32/commits/38c366302fb0f2afa10ce30086d2abdec9507c32
I'll add the permissions later today, but you can do it yourself: set the permissions, save the test data, and reload it.

**Comment by mambax7** [comment]
The permissions have been added:
https://github.com/XoopsModules25x/extcal/pull/33
