### ISSUE TITLE
error with remove me

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/extcal#28]
Remove me does not work!

**Comment by GregMage** [comment]
0.000345 - SELECT tu.uid, if(tu.name='', tu.uname, tu.name) AS name, tu.uname, tu.email, tm.status FROM extcal_eventnotmember tm, users tu WHERE tm.uid = tu.uid AND tm.event_id = 1
Error number: 1054
Error message: Champ 'tm.status' inconnu dans field list

0.000245 - DELETE FROM extcal_eventmember WHERE event_id = Array
Error number: 1054
Error message: Champ 'Array' inconnu dans where clause

0.000266 - SELECT tu.uid, if(tu.name='', tu.uname, tu.name) AS name, tu.uname, tu.email, tm.status FROM extcal_eventnotmember tm, users tu WHERE tm.uid = tu.uid AND tm.event_id = 1
Error number: 1054
Error message: Champ 'tm.status' inconnu dans field list

**Comment by mambax7** [comment]
Fixed in: https://github.com/XoopsModules25x/extcal/pull/34

**Comment by GregMage** [comment]
Perfect thank you
