### ISSUE TITLE
Error if you use import data

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/extcal#29]
When using data import, you can no longer edit an event! The system does not work!

**Comment by mambax7** [comment]
Steps to reproduce? What kind of data? The sample data? Your old data?

**Comment by GregMage** [comment]
1. 1. install extcal
2. extcal/admin/index.php and Import Sample Data (will delete ALL current data)
3. extcal/admin/event.php and edit an evant
the form does not appear

**Comment by alain01** [comment]
Humm,
Not tested but
I think it's a persmission problem.
May be sample data are imported with no permission, even for the group webmasters.
Could you check the permissions for the sample data, please ?

**Comment by GregMage** [comment]
I found the cause of the problem!

Permissions must be filled! I do not find it logical that the site admin (in administration) should have permissions. Normally the admin should be able to access. To avoid the problem, an error message should indicate that we do not have the rights to edit ...

**Comment by alain01** [comment]
;-) Les grands esprits se rencontrent !

**Comment by mambax7** [comment]
This should fix it: https://github.com/XoopsModules25x/extcal/pull/32/commits/38c366302fb0f2afa10ce30086d2abdec9507c32

**Comment by mambax7** [comment]
Can you maybe create a test file with French holidays?

**Comment by mambax7** [comment]
The permissions have been added: https://github.com/XoopsModules25x/extcal/pull/33
