### ISSUE TITLE
call to a member function getvars() on bool in  ExtcalPersistableObjectHandler line 596

### ISSUE THREAD

**Issue by djculex** [XoopsModules25x/extcal#41]
Adding the check for 0 value seems to fix it. Error popped up in events and categories if none existed.
org : if (null !== $object) {

changed:if (null !== $object && $object != 0) {

/**
     * @param        $object
     * @param string $format
     *
     * @return array
     */
    public function objectToArrayWithoutExternalKey($object, $format = 's')
    {
        $ret = [];
        if (null !== $object **&& $object != 0**) {
            $vars = $object->getVars();
            foreach ($vars as $k => $v) {
                $ret[$k] = $object->getVar($k, $format);
            }
        }

        return $ret;
    }

**Comment by mambax7** [comment]
How about:
if (!empty($object)) {

**Comment by djculex** [comment]
duh :-D yeah of course your right... 

if (!empty($object)) works fine obviously haha

**Comment by mambax7** [comment]
Can you submit a PR, so you'll get credit for finding this bug?
